/*
 * This file is part of munify, a free software.
 * Use, modification and distribution is subject to the BSD 2-clause license.
 * See accompanying file LICENSE.txt for its full text.
 */

#ifndef _MUNIFY_DETAIL_PREPROCESSOR_HPP_
#define _MUNIFY_DETAIL_PREPROCESSOR_HPP_

#include <boost/config.hpp>
#include <boost/preprocessor/debug/assert.hpp>
#include <boost/preprocessor/comparison/less_equal.hpp>
#include <boost/preprocessor/comma_if.hpp>

#ifndef MUNIFY_MAX_VARIADIC_ARGS
#define MUNIFY_MAX_VARIADIC_ARGS 16
#endif

#ifdef BOOST_NO_CXX11_VARIADIC_TEMPLATES

#include "empty.hpp"

#include <boost/preprocessor/repetition/enum.hpp>
#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/seq/elem.hpp>

#define MUNIFY_FORWARD_MACRO_FOR_EACH_VARIADIC_IDENTIFIER(Z, N, DATA) \
    BOOST_PP_ASSERT(BOOST_PP_LESS_EQUAL(N, MUNIFY_MAX_VARIADIC_ARGS)) \
    BOOST_PP_SEQ_ELEM(1, DATA)(BOOST_PP_CAT(BOOST_PP_SEQ_ELEM(0, DATA), N))

#define MUNIFY_FOR_EACH_VARIADIC_IDENTIFIER(N, PREFIX, MACRO) \
    BOOST_PP_ENUM(N, MUNIFY_FORWARD_MACRO_FOR_EACH_VARIADIC_IDENTIFIER, (PREFIX)(MACRO))

#define MUNIFY_VARIADIC_EMPTY_ARG(ARG) \
    detail::_

#define MUNIFY_VARIADIC_EMPTY_ARGS(N) \
    MUNIFY_FOR_EACH_VARIADIC_IDENTIFIER(N, _, MUNIFY_VARIADIC_EMPTY_ARG)

#define MUNIFY_TRAILING_VARIADIC_EMPTY_ARGS(N) \
    BOOST_PP_COMMA_IF(N) MUNIFY_VARIADIC_EMPTY_ARGS(N)

#define MUNIFY_VARIADIC_PARAM_DECLARATION(PARAM) \
    typename PARAM = MUNIFY_VARIADIC_EMPTY_ARG(_)

#define MUNIFY_VARIADIC_PARAMS_DECLARATION(N, PREFIX) \
    MUNIFY_FOR_EACH_VARIADIC_IDENTIFIER(N, PREFIX, MUNIFY_VARIADIC_PARAM_DECLARATION)

#define MUNIFY_VARIADIC_PARAM(PARAM) \
    typename PARAM

#define MUNIFY_VARIADIC_PARAMS(N, PREFIX) \
    MUNIFY_FOR_EACH_VARIADIC_IDENTIFIER(N, PREFIX, MUNIFY_VARIADIC_PARAM)

#define MUNIFY_VARIADIC_ARG(ARG) \
    ARG

#define MUNIFY_VARIADIC_ARGS(N, PREFIX) \
    MUNIFY_FOR_EACH_VARIADIC_IDENTIFIER(N, PREFIX, MUNIFY_VARIADIC_ARG)

#define MUNIFY_FOR_EACH_VARIADIC_ARG(N, PREFIX, MACRO) \
    MUNIFY_FOR_EACH_VARIADIC_IDENTIFIER(N, PREFIX, MACRO)

#else

#include <boost/preprocessor/if.hpp>
#include <boost/preprocessor/expr_if.hpp>
#include <boost/preprocessor/expand.hpp>
#include <boost/preprocessor/identity.hpp>
#include <boost/preprocessor/tuple/eat.hpp>

#define MUNIFY_VARIADIC_EMPTY_ARGS(N) \
    BOOST_PP_ASSERT(BOOST_PP_LESS_EQUAL(N, MUNIFY_MAX_VARIADIC_ARGS))

#define MUNIFY_TRAILING_VARIADIC_EMPTY_ARGS(N) \
    MUNIFY_VARIADIC_EMPTY_ARGS(N)

#define MUNIFY_VARIADIC_PARAMS_DECLARATION(N, PREFIX) \
    BOOST_PP_ASSERT(BOOST_PP_LESS_EQUAL(N, MUNIFY_MAX_VARIADIC_ARGS)) \
    BOOST_PP_EXPR_IF(N, typename...)

#define MUNIFY_VARIADIC_PARAMS(N, PREFIX) \
    BOOST_PP_ASSERT(BOOST_PP_LESS_EQUAL(N, MUNIFY_MAX_VARIADIC_ARGS)) \
    BOOST_PP_EXPR_IF(N, typename... PREFIX)

#define MUNIFY_VARIADIC_ARGS(N, PREFIX) \
    BOOST_PP_ASSERT(BOOST_PP_LESS_EQUAL(N, MUNIFY_MAX_VARIADIC_ARGS)) \
    BOOST_PP_EXPR_IF(N, PREFIX...)

#define MUNIFY_FOR_EACH_VARIADIC_ARG(N, PREFIX, MACRO) \
    BOOST_PP_IF(N, BOOST_PP_EXPAND, BOOST_PP_TUPLE_EAT(1))(MACRO BOOST_PP_IDENTITY((PREFIX))()...)

#endif

#define MUNIFY_TRAILING_VARIADIC_DEFAULTED_PARAMS(N, PREFIX) \
    BOOST_PP_COMMA_IF(N) MUNIFY_VARIADIC_PARAMS_DECLARATION(N, PREFIX)

#define MUNIFY_TRAILING_VARIADIC_PARAMS(N, PREFIX) \
    BOOST_PP_COMMA_IF(N) MUNIFY_VARIADIC_PARAMS(N, PREFIX)

#define MUNIFY_TRAILING_VARIADIC_ARGS(N, PREFIX) \
    BOOST_PP_COMMA_IF(N) MUNIFY_VARIADIC_ARGS(N, PREFIX)

#define MUNIFY_FOR_EACH_TRAILING_VARIADIC_ARG(N, PREFIX, MACRO) \
    BOOST_PP_COMMA_IF(N) MUNIFY_FOR_EACH_VARIADIC_ARG(N, PREFIX, MACRO)

#endif
